name: network_progress
description: Helpers for showing network progress and retrying failed requests
version: 0.1.0
author:
homepage:

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  equatable: '>=1.0.0 <2.0.0'
  building_blocs:
    git: 
      url: https://github.com/buntagonalprism/building_blocs.git
      ref: add-streams
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

